spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SergiySobolev/food-pal/tree/master/food-pal-config
server:
  port: 8888